import type { Metadata } from 'next';
import { Barlow_Semi_Condensed } from 'next/font/google';
import './globals.css';

const barlowSemiCondensed = Barlow_Semi_Condensed({
  subsets: ['latin'],
  display: 'swap',
  style: 'normal',
  weight: ['500', '600'],
  variable: '--font-barlow-semi-condensed',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${barlowSemiCondensed.variable}`}>{children}</body>
    </html>
  );
}
